[package]
name = "rust_actix_postgres_api"
version = "0.1.0"
edition = "2021"

# Dependencies
[dependencies]
actix-web = "4.9.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
deadpool-postgres = { version = "0.14.0" }
tokio-postgres = { version = "0.7", features = ["with-uuid-1"] }
tokio = { version = "1", features = ["full"] }
dotenvy = "0.15"
uuid = { version = "1.10.0", features = ["serde", "v4"] }
futures = "0.3"
bcrypt = "0.15.1"  # For password hashing
env_logger = "0.11.5"
log = "0.4"